-- =============================================================================
-- 007 — Esquema de las funciones que el repositorio avanzó mientras el equipo
--       trabajaba sobre el ZIP (commits 771e692 .. 79cbaff).
--
-- Por qué existe: el equipo exportó el proyecto en el commit 8cf057b y creó su
-- base de desarrollo con setup_dev_db.sql, que no contempla nada de lo que se
-- añadió después. Sin esta migración, la base de DEV no puede correr el código
-- reintegrado: el login por código de vendedor, el bloqueo de clientes y el
-- inventario de oficina fallan por columnas y tablas inexistentes.
--
-- Dónde ejecutarla: SOLO en el proyecto de DESARROLLO (vkrpvvqvtyyqqstyuchc).
-- En producción (vedgedsbuajueynnyvpn) estos objetos YA existen; la migración
-- es idempotente y aditiva, así que no rompería nada, pero no hace falta.
--
-- Los nombres van entre comillas donde el servidor usa camelCase: Postgres
-- pasa a minúsculas todo identificador sin comillas y las consultas de
-- Supabase no encontrarían la columna.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- users: código de vendedor y cierre de sesión forzado
-- (commits c621398, 9ca4e69, 7d9c580)
-- ---------------------------------------------------------------------------

-- Código con el que el vendedor inicia sesión, en lugar del correo.
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS "sellerCode" TEXT;

-- Marca de tiempo del último cierre forzado. requireAuth invalida cualquier
-- JWT emitido ANTES de esta fecha (server.ts, chequeo de force_logout_at).
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS force_logout_at TEXT;

-- Desde que el ingreso es por código, el correo dejó de ser obligatorio:
-- hay vendedores dados de alta sin dirección de correo.
ALTER TABLE public.users ALTER COLUMN email DROP NOT NULL;

-- El código se compara sin distinguir mayúsculas, así que la unicidad también
-- debe ser insensible a mayúsculas. Parcial para no chocar con los usuarios
-- que todavía no tienen código asignado.
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_sellercode
  ON public.users (lower("sellerCode"))
  WHERE "sellerCode" IS NOT NULL;

-- ---------------------------------------------------------------------------
-- login_tokens: tokens de un solo uso para el ingreso (commit 9ca4e69)
-- ---------------------------------------------------------------------------

-- Mismo DDL que server.ts intenta crear por RPC al arrancar. "usedAt" se
-- rellena al consumirlo: un token usado no vuelve a servir.
CREATE TABLE IF NOT EXISTS public.login_tokens (
  id          TEXT PRIMARY KEY,
  "userId"    TEXT NOT NULL,
  token       TEXT NOT NULL,
  "createdAt" TEXT NOT NULL,
  "usedAt"    TEXT,
  "expiresAt" TEXT
);

-- El login busca por (userId, token); el índice evita el scan completo.
CREATE INDEX IF NOT EXISTS idx_login_tokens_user
  ON public.login_tokens ("userId", token);

-- ---------------------------------------------------------------------------
-- clients: código de cliente y bloqueo (commits fbe10ce, 79cbaff)
-- ---------------------------------------------------------------------------

-- Código corto que el vendedor pide al cliente para verificar su identidad.
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS "clientCode" TEXT;

-- Cliente vetado: Ventas lo rechaza y Clientes avisa si alguien intenta
-- registrar otro con datos que coinciden.
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS "isBlocked" BOOLEAN DEFAULT FALSE;

-- ---------------------------------------------------------------------------
-- office_inventory: inventario de oficina (commit 771e692)
-- ---------------------------------------------------------------------------

-- No existe DDL de esta tabla en ninguna parte del repositorio:
-- office_inventory_setup.sql sólo desactiva RLS sobre una tabla que nunca se
-- llegó a crear. Las columnas salen del payload de POST /api/office-inventory.
-- El id se genera solo porque el endpoint no lo envía.
CREATE TABLE IF NOT EXISTS public.office_inventory (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT,
  category   TEXT,
  quantity   NUMERIC DEFAULT 0,
  unit_price NUMERIC DEFAULT 0,
  location   TEXT,
  status     TEXT
);

-- SOLO DEV: el resto de las tablas de esta base también están sin RLS
-- (setup_dev_db.sql lo hace explícito). En producción hay que definir
-- políticas antes de exponer la tabla.
ALTER TABLE public.office_inventory DISABLE ROW LEVEL SECURITY;

-- =============================================================================
-- Verificación
-- =============================================================================
-- Ambas consultas deben devolver todas las filas esperadas:
--
--   SELECT table_name FROM information_schema.tables
--    WHERE table_schema = 'public'
--      AND table_name IN ('login_tokens', 'office_inventory');
--
--   SELECT table_name, column_name FROM information_schema.columns
--    WHERE table_schema = 'public'
--      AND (   (table_name = 'users'   AND column_name IN ('sellerCode', 'force_logout_at'))
--           OR (table_name = 'clients' AND column_name IN ('clientCode', 'isBlocked')));
--
-- Nota: los productos críticos excluidos NO necesitan tabla. El servidor los
-- guarda como JSON en la columna photo de una fila de users con
-- id = 'sys-critical-config', igual que el resto de los blobs sys-*.
