 = C:\Program Files\Android\Android Studio\jbr
 = C:\Users\sesef\AppData\Local\Android\Sdk
C:/Users/sesef/.gemini/antigravity-ide/bin;C:\Program Files (x86)\Common Files\Oracle\Java\java8path;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA App\NvDLISR;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Program Files\HP\OMEN-Broadcast\Common;C:\Program Files\GitHub CLI\;C:\Program Files\nodejs\;C:\Users\sesef\AppData\Local\Microsoft\WindowsApps;C:\Users\sesef\AppData\Local\Programs\Antigravity IDE\bin;C:\Users\sesef\AppData\Roaming\npm;C:\Program Files\nodejs;C:\Program Files\GitHub CLI;C:\Program Files\Git\cmd;C:\Users\sesef\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\sesef\AppData\Local\Programs\DockerDesktop\resources\bin;C:\Users\sesef\AppData\Local\Programs\Amazon\AWSCLIV2\;C:\Users\sesef\AppData\Local\Programs\Ollama = C:\Program Files\Android\Android Studio\jbr\bin; + C:/Users/sesef/.gemini/antigravity-ide/bin;C:\Program Files (x86)\Common Files\Oracle\Java\java8path;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA App\NvDLISR;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Program Files\HP\OMEN-Broadcast\Common;C:\Program Files\GitHub CLI\;C:\Program Files\nodejs\;C:\Users\sesef\AppData\Local\Microsoft\WindowsApps;C:\Users\sesef\AppData\Local\Programs\Antigravity IDE\bin;C:\Users\sesef\AppData\Roaming\npm;C:\Program Files\nodejs;C:\Program Files\GitHub CLI;C:\Program Files\Git\cmd;C:\Users\sesef\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\sesef\AppData\Local\Programs\DockerDesktop\resources\bin;C:\Users\sesef\AppData\Local\Programs\Amazon\AWSCLIV2\;C:\Users\sesef\AppData\Local\Programs\Ollama

Write-Host Using JAVA_HOME: 
Write-Host Using ANDROID_HOME: 

cd android
.\gradlew.bat assembleDebug
