import { precacheAndRoute } from 'workbox-precaching';

declare const self: any;

// Precache all assets generated by Vite build
precacheAndRoute(self.__WB_MANIFEST || []);

// Handle Push Events
self.addEventListener('push', (event: any) => {
  let payload: any = {
    title: 'Agricovet',
    message: 'Nuevos datos disponibles'
  };

  if (event.data) {
    try {
      payload = event.data.json();
    } catch (err) {
      payload = {
        title: 'Agricovet',
        message: event.data.text()
      };
    }
  }

  const isDynamicTag = !payload.tag;
  const tag = payload.tag || `agricovet-notif-${Date.now()}`;

  const options = {
    body: payload.message || '',
    icon: '/agricovet.png',
    badge: '/agricovet.png',
    // Standard double-short vibration pattern
    vibrate: [200, 100, 200, 100, 200],
    sound: '/whatsapp.wav',
    data: {
      url: payload.url || '/'
    },
    actions: [
      { action: 'open', title: 'Ver en Agricovet' }
    ],
    tag: tag,
    renotify: isDynamicTag ? false : true,
    requireInteraction: true,
    silent: false
  };

  const clientsPromise = self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clients: any[]) => {
    clients.forEach((client) => {
      client.postMessage({
        type: 'PUSH_NOTIFICATION_RECEIVED',
        title: payload.title,
        message: payload.message
      });
    });
  });

  event.waitUntil(
    Promise.all([
      self.registration.showNotification(payload.title || 'Agricovet', options),
      clientsPromise
    ])
  );
});

// Handle Notification Click Event
self.addEventListener('notificationclick', (event: any) => {
  event.notification.close();
  
  const targetUrl = event.notification.data?.url || '/';

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList: any[]) => {
      // If a window is already open, focus it and navigate to the target url
      for (const client of clientList) {
        if (client.url.includes(self.location.origin)) {
          if ('focus' in client) {
            client.focus();
          }
          if ('navigate' in client) {
            client.navigate(targetUrl);
          }
          return;
        }
      }
      // If no window is open, open a new one
      if (self.clients.openWindow) {
        return self.clients.openWindow(targetUrl);
      }
    })
  );
});
